### ISSUE TITLE
Notifications refactoring

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/activitypods#91]
Currently we use a service which generate notifications based on activities and match patterns. But this won't work with external apps. The easiest will be for apps to take care themselves of sending notifications.

Apps can listen to inbox and outbox activity. If at any time a notification is needed, simply send a `Note` to the user (as the application itself). The user will receive it as a message from the app in question, and it will generate an email (or, in the future, a web-push notification)

To avoid duplication of notifications (e.g. two event apps each sending a notification when an invitation is received), simply add the URI of the activity in the `context`. If two apps send a notification for the same context, the "priority" app for that type of resource (?) is selected, and the other ignored.

## Possible format

```json
{
  "type": "Note",
  "actor": "https://welcometomyplace.org/data/app",
  "name": "Alice invites you to an event: my birthday party !",
  "content": "You have received an invitation from Alice",
  "url": [
    {
      "type": "Link",
      "name": "View",
      "href": "https://welcometomyplace.org/Event/{eventUri}/show"
    },
    {
      "type": "Link",
      "name": "Ignore future Alice invitations",
      "href": "https://welcometomyplace.org/Event/{eventUri}/show?action=ignore"
    }
  ],
  "context": "https://mypod.store/alice/data/{uuid}"
}
```

## Issues

- Apps will have priority based on resources types. But activities don't indicate resources types. Should we put the object in the context instead ? Or in a `object` predicate ? Or should we read the activity and find the object from there ?
- To solve #82, maybe apps could also put a geolocalisation to their messages ?

**Comment by Laurin-W** [comment]
> Apps will have priority based on resources types. But activities don't indicate resources types. Should we put the object in the context instead ? Or in a object predicate ? Or should we read the activity and find the object from there ?

Looking at the [`context` predicate](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-context) and [`Invite` activity type](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-invite), I'd say that the `object` predicate is the way to go, since the `object` there is the thing being invited to (in their case by an `Invite` activity, here with a `Note`).

Maybe I'm thinking in the wrong direction but is it even possible for a client to tell in advance, if the `object` is just an id reference or resolved? For performance-purposes, I'd argue it makes sense, to add the invite event to the object and not just the reference.

**Comment by srosset81** [comment]
Why are you mentioning the `Invite` activity? Do you think `Invite` activities should be used for notifications ? For me, `Invite` activities have always been about "inviting for an event", like in the example provided in the AS spec. But maybe it could be extended for other purposes ?

**Comment by Laurin-W** [comment]
I looked at the `Invite` activity since it matched the use case here. I'm not sure, if it is a good idea in general, to use it for notification but it seemed suitable in the case. I don't have much experience with ActivityStreams types though, by intution I would have probably chosen an activity and not an object type. In the ActivityStreams spec, the [Announce](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-announce) is described like this:
>  Indicates that the actor is calling the target's attention the object. The origin typically has no defined meaning.  "

That sounded pretty much fitting the needs here, but the ActivityPub spec, the [Announce](https://www.w3.org/TR/activitypub/#announce-activity-inbox) activity is only mentioned in the server-server spec, it says:
>  Upon receipt of an Announce activity in an inbox, a server SHOULD increment the object's count of [shares](https://www.w3.org/TR/activitypub/#shares) by adding the received activity to the shares collection if this collection is present.
> NOTE: The Announce activity is effectively what is known as "sharing", "reposting", or "boosting" in other social networks. 

So, maybe this could cause some unwanted side-effects?

**Comment by srosset81** [comment]
Oh I understand! The example above is only meant to be an example, but the idea is to have a common language for all notifications, no matter what message is inside. Applications will listen to activities received on the Inbox (and this can include `Invite` activities) and convert them to Note. This way the Pod provider doesn't have to think about the type of activity being sent, it only sees it is a message from a registered application, and it converts it to an email.

In ActivityPub world, the simplest way to send a message is to send a `Note`. This is converted to the server as a `Create` activity. In my opinion, the simplest way for an `Application` to send a notification to a `Person` is thus to send him/her a `Note`. 

(The `Announce` activity is only meant for "reposting", it is not meant for a general use case. All activities could be considered as announcements in some sense... We currently use it too much on ActivityPods. That's why I'm thinking about using a new new `Authorize` activity to notify that a resource has been shared with someone).

**Comment by Laurin-W** [comment]
Ah ok, thanks for the clarification, that sounds like a decent and generic way to go!

How would the pod provider know, if the message is to be sent by email / is an application notification? Or does the pod provider just convert enverything to an email?

**Comment by srosset81** [comment]
Notes are already used for direct messages between users. If the pod provider detects the sender is a registered application, the email will probably look differently
